-- Drop all TENOUCHI tables (run this first if tables exist)

DROP TABLE IF EXISTS secretary_logs CASCADE;
DROP TABLE IF EXISTS contacts CASCADE;
DROP TABLE IF EXISTS family_events CASCADE;
DROP TABLE IF EXISTS notes CASCADE;
DROP TABLE IF EXISTS stash_settings CASCADE;
DROP TABLE IF EXISTS stash CASCADE;
DROP TABLE IF EXISTS money_records CASCADE;
DROP TABLE IF EXISTS timeline_items CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP FUNCTION IF EXISTS update_updated_at CASCADE;
DROP FUNCTION IF EXISTS get_stash_balance CASCADE;
